services:
  user-service:
    container_name: user_container
    build:
      context: .
      target: development
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "8080:3000"
    volumes:
      - ./src:/app/src  # Mount local project folder into the container
      - /app/node_modules  # Prevent overwriting node_modules

